version: '3.8'

services:
  global-ai-brain:
    build: .
    container_name: global_ai_brain_node
    ports:
      - "4005:4005"
    volumes:
      - global_brain_data:/opt
    environment:
      - PORT=4005
      - GEMINI_API_KEY=AIzaSyCanOYHuNzjlw9eH6-KOe5xDt3OG8LmtKc
    restart: always

volumes:
  global_brain_data:
    driver: local
